name: retrofit_flutter
description: retrofit for flutter
version: 1.0.5
homepage: https://github.com/PureAway/retrofit_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  dio: ^4.0.0
  source_gen: ^1.0.0
  built_collection: ^5.0.0
  code_builder: ^4.0.0
  tuple: ^2.0.0
  analyzer: ^2.0.0
  dart_style: ^2.0.0
  build: ^2.0.0
  collection: ^1.15.0