name: retrofit_flutter
description: retrofit for flutter
version: 0.0.4
homepage: https://github.com/PureAway/retrofit_flutter

environment:
  sdk: ">=2.8.2 <3.0.0"

dependencies:
  meta: ^1.1.8
  dio: ^3.0.10
  source_gen: '>=0.9.4+6 <0.9.4+7'
  built_collection: ^4.2.0
  code_builder: ^3.2.0
  tuple:    ^1.0.2
  analyzer: '>=0.39.10 <0.39.12'
  dart_style: ^1.3.3
  build:  ^1.2.2
flutter: